from django.urls import path , include
from . import views
from .next_level import next_level_urls
urlpatterns = [
    path('', views.index, name='index'),
    path('python/', views.python, name='python'),
    path('java/', views.java, name='java'),
    path('php/', views.php, name='php'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('send_otp/', views.send_otp, name='send_otp'),
    path('logout/', views.logout, name='logout'),
    path('enter_email/', views.enter_email, name='enter_email'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('change_password/', views.change_password, name='change_password'),
    path('add_books/', views.add_books, name='add_books'),
    path('view_books/', views.view_books, name='view_books'),
    path('more_details/<int:pk>/', views.more_details, name='more_details'),
    path('user_more_detail/<int:pk>/', views.user_more_detail, name='user_more_detail'),
    path('remove_book/<int:pk>/', views.remove_book, name='remove_book'),
    path('search_book/', views.search_book, name='search_book'),
    path('inactive_books/', views.inactive_books, name='inactive_books'),
    path('active_book/<int:pk>/', views.active_book, name='active_book'),
    path('active_book/<int:pk>/', views.active_book, name='active_book'),
    path('add_cart/<int:pk>/', views.add_cart, name='add_cart'),
    path('edit_profile/', views.profile, name='profile'),
    path('add_cart/<int:pk>/', views.add_cart, name='add_cart'),
    path('view_cart/', views.view_cart, name='view_cart'),
    path('remove_cart/<int:pk>/', views.remove_cart, name='remove_cart'),
    path('remove_checkout/<int:pk>/', views.remove_checkout, name='remove_checkout'),
    path('remove_wish/<int:pk>/', views.remove_wish, name='remove_wish'),
    path('add_wishlist/<int:pk>/', views.add_wishlist, name='add_wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('all_book/', views.all_book, name='all_book'),
    path('help/', views.help_me, name='help'),
    path('sort1/', views.sort1, name='sort1'),
    path('sort2/', views.sort2, name='sort2'),
    path('sort3/', views.sort3, name='sort3'),
    path('sort4/', views.sort4, name='sort4'),
    path('filter1/', views.filter1, name='filter1'),
    path('order_detail/', views.initiate_payment, name='order_details'),
    path('callback/', views.callback, name='callback'),
    path('orders/', views.my_orders, name='orders'),
    # path('checkout/', views.checkout, name='checkout'),
    # path("create-payment-intent", views.createpayment, name="create-payment-intent"),
    # path("payment-complete", views.paymentcomplete, name="payment-complete"),
    path('pay/',views.my_ck,name='payment'),


] + next_level_urls.urlpatterns
