# Generated by Django 3.1 on 2020-08-21 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_price', models.CharField(max_length=10)),
                ('book_author', models.CharField(max_length=30)),
                ('book_category', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('php', 'php')], default='', max_length=30)),
                ('book_desc', models.TextField()),
                ('book_image', models.ImageField(upload_to='images/')),
                ('book_status', models.CharField(default='active', max_length=30)),
                ('quantity', models.CharField(default=0, max_length=10)),
                ('seller_email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('account_type', models.CharField(default='user', max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('pas', models.CharField(max_length=30)),
                ('cpas', models.CharField(max_length=30)),
                ('user_image', models.ImageField(default='', upload_to='images/')),
                ('status', models.CharField(default='inactive', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=datetime.datetime(2020, 8, 21, 11, 31, 48, 812157))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('order_email', models.CharField(default='', max_length=50)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('zip_code', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('mobile', models.CharField(max_length=12)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2020, 8, 21, 11, 31, 48, 812624))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=datetime.datetime(2020, 8, 21, 11, 31, 48, 811767))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
