# Generated by Django 3.0.8 on 2020-09-13 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200821_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_main_title', models.CharField(max_length=100)),
                ('offer_sub_title', models.CharField(max_length=100)),
                ('offer_image', models.ImageField(upload_to='images/')),
                ('offer_redirection_url', models.URLField()),
                ('offer_active_date', models.DateTimeField(auto_now_add=True)),
                ('offer_expire_date', models.DateTimeField()),
                ('payment_price', models.CharField(max_length=10)),
                ('payment', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 17, 12, 10, 391549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 17, 12, 10, 393545, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 17, 12, 10, 392548, tzinfo=utc)),
        ),
    ]
