# Generated by Django 3.0.8 on 2020-09-13 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200913_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_banner',
            name='offer_expire_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 17, 20, 4, 76273, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer_banner',
            name='offer_active_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 17, 20, 4, 77272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 17, 20, 4, 76273, tzinfo=utc)),
        ),
    ]
