# Generated by Django 3.0.8 on 2020-09-13 17:31

import app1.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200913_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 17, 31, 9, 571024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer_banner',
            name='offer_active_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='offer_banner',
            name='offer_expire_date',
            field=models.DateField(default=app1.models.get_expire),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 17, 31, 9, 575048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 17, 31, 9, 571024, tzinfo=utc)),
        ),
    ]
