# Generated by Django 3.0.8 on 2020-09-14 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200913_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 11, 55, 33, 187082, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer_banner',
            name='payment_price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 11, 55, 33, 188050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 11, 55, 33, 188050, tzinfo=utc)),
        ),
    ]
