# Generated by Django 3.0.5 on 2020-09-15 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200914_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_banner',
            name='expire',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 15, 59, 18, 95892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 15, 59, 18, 96892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 15, 59, 18, 96319, tzinfo=utc)),
        ),
    ]
