# Generated by Django 2.2.7 on 2020-09-19 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200915_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer_banner',
            old_name='expire',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 5, 33, 47, 717193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer_banner',
            name='payment_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 5, 33, 47, 718191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 5, 33, 47, 717193, tzinfo=utc)),
        ),
    ]
