# Generated by Django 2.2.14 on 2020-09-17 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200917_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 5, 38, 5, 121424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer_banner',
            name='expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 5, 38, 5, 122347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 5, 38, 5, 121817, tzinfo=utc)),
        ),
    ]
