# Generated by Django 2.2.7 on 2020-09-19 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200919_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='website_url',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 5, 52, 46, 95097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 5, 52, 46, 96094, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 5, 52, 46, 95097, tzinfo=utc)),
        ),
    ]
