# Generated by Django 2.2.7 on 2020-09-19 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200919_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(choices=[('python', 'python'), ('java', 'java'), ('php', 'php'), ('react', 'react'), ('scala', 'scala'), ('c', 'c'), ('other', 'other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='website_url',
            field=models.SlugField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 5, 57, 11, 494399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 5, 57, 11, 495394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 5, 57, 11, 495394, tzinfo=utc)),
        ),
    ]
