# Generated by Django 2.2.7 on 2020-09-19 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20200919_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 10, 20, 13, 609653, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 10, 20, 13, 614689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 10, 20, 13, 611447, tzinfo=utc)),
        ),
    ]
